// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type Node interface {
	IsNode()
}

type Account struct {
	Email string          `json:"email"`
	Notes *NoteConnection `json:"notes"`
}

type NoteConnection struct {
	Edges    []*NoteEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type NoteEdge struct {
	Node   *Note  `json:"node"`
	Cursor string `json:"cursor"`
}

type NoteInput struct {
	Title    string  `json:"title"`
	Contents *string `json:"contents"`
}

type PageInfo struct {
	HasNextPage     bool   `json:"hasNextPage"`
	HasPreviousPage bool   `json:"hasPreviousPage"`
	EndCursor       string `json:"endCursor"`
	StartCursor     string `json:"startCursor"`
}
